### ISSUE TITLE
Bad interaction with SDL RenderPresent?

### ISSUE THREAD

**Issue by cmatsuoka** [blackjack/webcam#6] opened 2016-05-18 12:17 UTC
I'm experiencing a rather strange problem related to v4l2 frame reading: whenever `ReadFrame()` is called (or, more, precisely, the buffer enqueuing/dequeuing ioctls), SDL screen updates stop or happen at random, large intervals. Exact behavior seems to be different on different machines. I don't know if the problem is in V4L2, SDL, the GL stack, X11,  drm, or my code. I still didn't try to reimplement the example in C to bypass the Go packages, but it doesn't seem that Go is causing this.

Perhaps you could try the following example to see if you have any idea on what's happening here? This code should show a smooth color change in the SDL window, but fails to do so if `cam.ReadFrame()` is uncommented. The frame counter shows that `ReadFrame()` is not blocking, it's just the window image that's not being properly updated.

    package main

    import (
    	"fmt"
    	"github.com/blackjack/webcam"
    	"github.com/veandco/go-sdl2/sdl"
    	"os"
    )
    
    func main() {
    	window, err := sdl.CreateWindow("test", sdl.WINDOWPOS_UNDEFINED,
    		sdl.WINDOWPOS_UNDEFINED, 640, 480, sdl.WINDOW_SHOWN)
    	if err != nil {
    		fmt.Printf("can't create window: %s\n", err)
    		os.Exit(1)
    	}
    	defer window.Destroy()
    
    	renderer, err := sdl.CreateRenderer(window, -1, sdl.RENDERER_ACCELERATED)
    	if err != nil {
    		fmt.Printf("can't create renderer: %s\n", err)
    		os.Exit(1)
    	}
    	defer renderer.Destroy()
    
    	texture, err := renderer.CreateTexture(sdl.PIXELFORMAT_YUY2, sdl.TEXTUREACCESS_STREAMING, 640, 480)
    	if err != nil {
    		fmt.Printf("can't create texture: %s", err)
    		os.Exit(1)
    	}
    	defer texture.Destroy()
    
    	x := uint8(0)
    
    	cam, err := webcam.Open("/dev/video0")
    	if err != nil {
    		fmt.Printf("can't open webcam: %s", err)
    		os.Exit(1)
    	}
    	_, _, _, err = cam.SetImageFormat(0x56595559, 640, 480)
    	if err != nil {
    		fmt.Printf("can't set image format: %s", err)
    		os.Exit(1)
    	}
    	cam.StartStreaming()
    
    	for {
    		cam.WaitForFrame(1)
    		cam.ReadFrame()
    		renderer.SetDrawColor(x, x, x, 255)
    		x++
    		renderer.Clear()
    		renderer.Present()
    		fmt.Printf("%03d\r", x)
    	}
    }

**Comment by blackjack** [comment] 2016-05-18 12:23
Duplicate of #5

**Closed** 2016-05-18 12:23 UTC
